### PR TITLE
Check chip missing

### PR DESCRIPTION
**Pull request by dronov**
Hi!

I was very tired to see empty chip ID and other tech info. 
So I decided to make a readable message when chip is missing in ch341.
@setarcos what do you think?

### CODE REVIEW

**Comment by dronov** [comment]
Up

**Comment by cg9999** [comment]
+    if (in[1] != 0xFF && in[2] != 0xFF && in[3] != 0xFF)
+    {
+        printf("Manufacturer ID: %02x\n", in[1]);
+        printf("Memory Type: %02x%02x\n", in[2], in[3]);

Are you sure 0xff is not valid value in memory type bytes?

**Comment by dronov** [comment]
@cg9999 I think so, usually 0xFF in spi id means that this is a corrupt flash, wrong connection on other. Also this program can't work with 0xFF in readed spi id. 
Another example: U-boot can't load flash with 0xFF in readed spi id, cause no spi-memory defined in source code with if 0xFF 0xFF 0xFF.

**Comment by cg9999** [comment]
But your expression won't allow any of the bytes to be 0xff.
For example hypothetical memory from manufacturer 0x12, memory type 0x34,0xff would not be detected

**Comment by dronov** [comment]
@cg9999 I try to correct only this case: 
```
sudo ch341prog -e
Device reported its revision [4.03]
Manufacturer ID: ff
Memory Type: ffff
No CFI structure found, trying to get capacity from device ID. Set manually if detection fails.
Capacity: ff
Chip capacity is -2147483648 bytes
```

**Comment by cg9999** [comment]
I know. The expression (in[1]==0xff && in[2]==0xff && in[3]==0xff) would detect that case

so you could write the if as 
if (! (in[1]==0xff && in[2]==0xff && in[3]==0xff)) {
  // good memory
} else {
  // not detected
}

**Comment by dronov** [comment]
@cg9999 of course.
My colleague says that sometimes occurs interesting cases from noname vendors, and no one knows parameters for writing. E.g. Minipro Programmer has an option 'check id', and if you do not choose this option, minipro will try to force program the spi you've entered with parameters from another spi, e.g. W25Q128

Maybe it would be useful to have a flag in ch341prog and force program with entered Manufactured ID and memory type.

**Pull request merged**
